# Module 15 — Logistic Regression Practice Problems
### Titanic Survival Prediction

এই notebook-এ Module 15-এর প্রতিটি topic-এর উপর হাতে-কলমে practice করবে।
প্রতিটি problem-এর নিচে code cell-এ solution লিখো।

**Dataset:** `titanic_data_updated.csv`

---
### Problem 1 — Imports and Data Loading

নিচের সব library import করো:
- `numpy`, `pandas`
- `sklearn` থেকে: `train_test_split`, `SimpleImputer`, `OrdinalEncoder`, `OneHotEncoder`, `LabelEncoder`, `StandardScaler`, `MinMaxScaler`, `Pipeline`, `ColumnTransformer`, `LogisticRegression`

`titanic_data_updated.csv` লোড করো `df` নামে এবং প্রথম 5টি row দেখাও।

In [1]:
# YOUR CODE HERE
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder,LabelEncoder,StandardScaler,MinMaxScaler

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer


from sklearn.linear_model import LogisticRegression

In [3]:

# Load the dataset from a CSV file into a pandas DataFrame
df = pd.read_csv('titanic_data_updated.csv')


# Display 5 random rows to see what the data looks like
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
735,736,no,third,"Williams, Mr. Leslie",male,28.5,0,0,54636,16.1000,NaN,S
73,74,no,third,"Chronopoulos, Mr. Apostolos",male,26.0,1,0,2680,14.4542,NaN,C
711,712,no,first,"Klaber, Mr. Herman",male,NaN,0,0,113028,26.5500,C124,S
155,156,no,first,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
743,744,no,third,"McNamee, Mr. Neal",male,24.0,1,0,376566,16.1000,NaN,S

---
### Problem 2 — Feature Engineering

দুটি নতুন column তৈরি করো:

1. `Family_Size` — formula: `SibSp + Parch + 1`
2. `Deck` — `Cabin` column-এর NaN গুলো `"Missing"` দিয়ে fill করো, তারপর প্রথম character নিয়ে `Deck` column তৈরি করো

শেষে `df.sample(5)` দিয়ে result দেখাও।

In [4]:
# YOUR CODE HERE
df["Family_Size"] = df["SibSp"] + df['Parch']+ 1

new_order = [
    'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
    'SibSp', 'Parch', 'Family_Size',  # <--- Ekhane SibSp ar Parch er pore niye asa holo
    'Ticket', 'Fare', 'Cabin', 'Embarked']
df = df[new_order]


df['Cabin']= df['Cabin'].fillna('Missing')
df['Embarked']= df['Embarked'].fillna('Unknown')


df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Family_Size,Ticket,Fare,Cabin,Embarked
478,479,no,third,"Karlsson, Mr. Nils August",male,22.0,0,0,1,350060,7.5208,Missing,S
545,546,no,first,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,1,693,26.0000,Missing,S
760,761,no,third,"Garfirth, Mr. John",male,NaN,0,0,1,358585,14.5000,Missing,S
576,577,yes,second,"Garside, Miss. Ethel",female,34.0,0,0,1,243880,13.0000,Missing,S
825,826,no,third,"Flynn, Mr. John",male,NaN,0,0,1,368323,6.9500,Missing,Q

In [5]:
df['Cabin'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: Cabin
Non-Null Count  Dtype
--------------  -----
891 non-null    object
dtypes: object(1)
memory usage: 7.1+ KB

In [8]:
df['Deck'] = df['Cabin'].astype(str).str[0]
df.sample(5)


df['Deck'].value_counts()

Deck
M    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

---
### Problem 3 — X and y Split

`df` থেকে features এবং target আলাদা করো:

- `X` = `Survived` বাদে সব column
- `y` = শুধু `Survived` column

`X.shape` এবং `y.shape` print করো।

In [11]:
# YOUR CODE HERE
X = df.drop('Survived', axis=1)
y = df['Survived']

print(X.shape)
print(y.shape)

(891, 13)
(891,)

---
### Problem 4 — Train-Test Split

`train_test_split` ব্যবহার করে `X_train`, `X_test`, `y_train`, `y_test` তৈরি করো।

Parameters:
- `test_size = 0.2`
- `random_state = 42`
- `stratify = y`

`X_train` এবং `X_test`-এর shape print করো।

In [13]:
# YOUR CODE HERE
X_train, X_test, y_train, y_test = train_test_split(
                                  X, y,
                                  test_size=0.2, random_state=42, stratify=y
                                  )

print(X_train.shape)
print(X_test.shape)

(712, 13)
(179, 13)

---
### Problem 5 — Outlier Handling

**Age column — Z-score method (rows remove করো):**
- `Z_score = (Age - mean) / std`
- যেসব row-এ `|Z_score| > 3`, সেগুলো `X_train` এবং `y_train` থেকে বাদ দাও

**Fare column — IQR clipping (rows রাখো, values clip করো):**
- `Q1` = 25th percentile, `Q3` = 75th percentile
- `IQR = Q3 - Q1`
- `minimum = max(0, Q1 - 1.5 * IQR)`
- `maximum = Q3 + 1.5 * IQR`
- `clip()` দিয়ে Fare column-কে `[minimum, maximum]` range-এ রাখো

In [14]:
# YOUR CODE HERE
mean_age = X_train['Age'].mean()
std_age = X_train['Age'].std()

X_train['Z_score'] = (X_train['Age'] - mean_age) / std_age

musk = (abs(X_train['Z_score']) <= 3)

X_train = X_train[musk]
y_train = y_train[musk]

# fare

fare_Q1 = X_train['Fare'].quantile(0.25)
fare_Q3 = X_train['Fare'].quantile(0.75)

IQR = fare_Q3 - fare_Q1

minimum = max(0 , fare_Q1 - 1.5 * IQR)
maximum = fare_Q3 + 1.5 * IQR

X_train['Fare'] = X_train['Fare'].clip(minimum, maximum)

---
### Problem 6 — Numerical Pipelines

দুটি numerical pipeline তৈরি করো:

**p1** — `Age` column-এর জন্য:
- Step 1: `SimpleImputer(strategy='mean')`
- Step 2: `StandardScaler()`

**p2** — `Fare` এবং `Family_Size` column-এর জন্য:
- Step 1: `SimpleImputer(strategy='median')`
- Step 2: `MinMaxScaler()`

In [16]:
# YOUR CODE HERE
# pipeline Numirical

p1 = Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='mean')),
        ('scaler',StandardScaler())
    ]
)

p2 = Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='median')),
        ('scaler',MinMaxScaler())
    ]
)
p1
p2

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', MinMaxScaler())])

---
### Problem 7 — Categorical Pipelines and ColumnTransformer

দুটি categorical pipeline তৈরি করো:

**p3** — `Embarked`, `Sex`, `Deck` column-এর জন্য:
- Step 1: `SimpleImputer(strategy='most_frequent')`
- Step 2: `OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore')`

**p4** — `Pclass` column-এর জন্য:
- `categories = [['third', 'second', 'first']]`
- Step 1: `SimpleImputer(strategy='most_frequent')`
- Step 2: `OrdinalEncoder(categories=categories)`
- Step 3: `MinMaxScaler()`

তারপর `ColumnTransformer` দিয়ে `preprocessor` তৈরি করো:
- `pipeline_1` → `p1` → `['Age']`
- `pipeline_2` → `p2` → `['Fare', 'Family_Size']`
- `pipeline_3` → `p3` → `['Embarked', 'Sex', 'Deck']`
- `pipeline_4` → `p4` → `['Pclass']`
- `remainder='drop'`

In [18]:
# YOUR CODE HERE
categories = [['third','second','first']]

# pipeline
#  categorical columns

p3 = Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('encoder',OneHotEncoder(sparse_output=False,drop='first',handle_unknown='ignore'))
    ]
)

p4 = Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('encoder',OrdinalEncoder(categories=categories)),
        ('scaler',MinMaxScaler())]
        )

---
### Problem 8 — Target Column Encoding

`y_train` এবং `y_test`-এ এখন `"yes"` এবং `"no"` string আছে। Model train করার আগে এগুলো numeric করতে হবে।

- `LabelEncoder` দিয়ে `y_train` এবং `y_test` encode করো
- encode করার আগে এবং পরে unique values print করো

In [19]:
# YOUR CODE HERE
le = LabelEncoder()

le.fit(y_train)

y_train = le.transform(y_train)
y_test = le.transform(y_test)

---
### Problem 9 — Model Training and Prediction

`lr_model` নামে একটি final `Pipeline` তৈরি করো:
- Step 1: `preprocessor` (Problem 7-এ তৈরি করা)
- Step 2: `LogisticRegression(class_weight='balanced', max_iter=1000)`

তারপর:
- `lr_model.fit()` দিয়ে `X_train` এবং `y_train` দিয়ে model train করো
- `predict()` দিয়ে `X_test`-এর prediction করো, `y_pred` নামে save করো
- প্রথম 10টি prediction print করো

In [22]:
# YOUR CODE HERE

preprocessor = ColumnTransformer(
    transformers=[
        ('pipeline_1',p1,['Age']),
        ('pipeline_2',p2,['Fare','Family_Size']),
        ('pipeline_3',p3,['Embarked','Sex','Deck']),
        ('pipeline_4',p4,['Pclass'])
    ],
    remainder='drop'

)

In [23]:
lr_model = Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('model',LogisticRegression(class_weight='balanced',max_iter=1000))
    ]
)
lr_model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('pipeline_1',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age']),
                                                 ('pipeline_2',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Fare', 'Family_Size']),
                                                 ('pipeline_3',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strateg...
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Embarked', 'Sex', 'Deck']),
                                                 ('pipeline_4',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder(categories=[['third',
                                                                                               'second',
                                                                                               'first']])),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Pclass'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

---
### Problem 10 — Evaluation

`sklearn.metrics` থেকে `accuracy_score`, `precision_score`, `recall_score` import করো।

`y_test` এবং `y_pred` দিয়ে তিনটি score calculate করো এবং নিচের format-এ print করো:

```
Accuracy  : 0.xx
Precision : 0.xx
Recall    : 0.xx
```

In [24]:
lr_model.fit(X_train,y_train)

lr_model['model'].coef_
lr_model['model'].intercept_
lr_model['model'].classes_

array([0, 1])

In [25]:
# YOUR CODE HERE
y_pred = lr_model.predict(X_test)

lr_model.predict_proba(X_test)

array([[0.85526115, 0.14473885],
       [0.92585208, 0.07414792],
       [0.7666301 , 0.2333699 ],
       [0.92801033, 0.07198967],
       [0.37660805, 0.62339195],
       [0.44238046, 0.55761954],
       [0.25270683, 0.74729317],
       [0.59796523, 0.40203477],
       [0.47968315, 0.52031685],
       [0.78364905, 0.21635095],
       [0.8621186 , 0.1378814 ],
       [0.81680817, 0.18319183],
       [0.33890802, 0.66109198],
       [0.70246038, 0.29753962],
       [0.14975119, 0.85024881],
       [0.83774933, 0.16225067],
       [0.46573884, 0.53426116],
       [0.86481338, 0.13518662],
       [0.79276925, 0.20723075],
       [0.23744971, 0.76255029],
       [0.86481338, 0.13518662],
       [0.1991492 , 0.8008508 ],
       [0.86652566, 0.13347434],
       [0.46127614, 0.53872386],
       [0.86184692, 0.13815308],
       [0.02715049, 0.97284951],
       [0.67634473, 0.32365527],
       [0.6359975 , 0.3640025 ],
       [0.81348342, 0.18651658],
       [0.80965131, 0.19034869],
       [0.88447964, 0.11552036],
       [0.01580968, 0.98419032],
       [0.84831434, 0.15168566],
       [0.63911809, 0.36088191],
       [0.77253434, 0.22746566],
       [0.74152839, 0.25847161],
       [0.76608364, 0.23391636],
       [0.38970412, 0.61029588],
       [0.8621186 , 0.1378814 ],
       [0.17556205, 0.82443795],
       [0.79553107, 0.20446893],
       [0.0139581 , 0.9860419 ],
       [0.86136629, 0.13863371],
       [0.13608584, 0.86391416],
       [0.23355509, 0.76644491],
       [0.81763144, 0.18236856],
       [0.86347551, 0.13652449],
       [0.49893723, 0.50106277],
       [0.14457824, 0.85542176],
       [0.20557778, 0.79442222],
       [0.04810421, 0.95189579],
       [0.36351414, 0.63648586],
       [0.3584603 , 0.6415397 ],
       [0.74451965, 0.25548035],
       [0.01781218, 0.98218782],
       [0.84626631, 0.15373369],
       [0.87352939, 0.12647061],
       [0.28348476, 0.71651524],
       [0.2862927 , 0.7137073 ],
       [0.59759032, 0.40240968],
       [0.3040018 , 0.6959982 ],
       [0.28821802, 0.71178198],
       [0.78505104, 0.21494896],
       [0.8378107 , 0.1621893 ],
       [0.43050853, 0.56949147],
       [0.30182002, 0.69817998],
       [0.05441266, 0.94558734],
       [0.87899146, 0.12100854],
       [0.60033495, 0.39966505],
       [0.69780421, 0.30219579],
       [0.10476239, 0.89523761],
       [0.81825882, 0.18174118],
       [0.42479531, 0.57520469],
       [0.02445387, 0.97554613],
       [0.77096081, 0.22903919],
       [0.92641087, 0.07358913],
       [0.88862726, 0.11137274],
       [0.85893508, 0.14106492],
       [0.588054  , 0.411946  ],
       [0.29571011, 0.70428989],
       [0.79393456, 0.20606544],
       [0.82043833, 0.17956167],
       [0.86863764, 0.13136236],
       [0.84654729, 0.15345271],
       [0.28100932, 0.71899068],
       [0.35255573, 0.64744427],
       [0.87991809, 0.12008191],
       [0.38143314, 0.61856686],
       [0.37955646, 0.62044354],
       [0.02229706, 0.97770294],
       [0.4478603 , 0.5521397 ],
       [0.44883224, 0.55116776],
       [0.91861892, 0.08138108],
       [0.864955  , 0.135045  ],
       [0.54659772, 0.45340228],
       [0.18189   , 0.81811   ],
       [0.38055729, 0.61944271],
       [0.8621186 , 0.1378814 ],
       [0.88862726, 0.11137274],
       [0.84910998, 0.15089002],
       [0.7677247 , 0.2322753 ],
       [0.01895887, 0.98104113],
       [0.35817424, 0.64182576],
       [0.08758116, 0.91241884],
       [0.8464324 , 0.1535676 ],
       [0.37502279, 0.62497721],
       [0.6286831 , 0.3713169 ],
       [0.864955  , 0.135045  ],
       [0.80504452, 0.19495548],
       [0.55209382, 0.44790618],
       [0.8621186 , 0.1378814 ],
       [0.94113988, 0.05886012],
       [0.85180804, 0.14819196],
       [0.39389326, 0.60610674],
       [0.18127698, 0.81872302],
       [0.8621186 , 0.1378814 ],
       [0.77288069, 0.22711931],
       [0.78313284, 0.21686716],
       [0.84550881, 0.15449119],
       [0.82494638, 0.17505362],
       [0.85684258, 0.14315742],
       [0.27393842, 0.72606158],
       [0.92041347, 0.07958653],
       [0.3198647 , 0.6801353 ],
       [0.79867438, 0.20132562],
       [0.76257539, 0.23742461],
       [0.41573152, 0.58426848],
       [0.40321898, 0.59678102],
       [0.83804435, 0.16195565],
       [0.5189141 , 0.4810859 ],
       [0.81383212, 0.18616788],
       [0.85693895, 0.14306105],
       [0.37660805, 0.62339195],
       [0.86294955, 0.13705045],
       [0.56714379, 0.43285621],
       [0.80949944, 0.19050056],
       [0.02628408, 0.97371592],
       [0.8621186 , 0.1378814 ],
       [0.35824199, 0.64175801],
       [0.86475594, 0.13524406],
       [0.44016808, 0.55983192],
       [0.77750933, 0.22249067],
       [0.21083786, 0.78916214],
       [0.5239119 , 0.4760881 ],
       [0.7795452 , 0.2204548 ],
       [0.62807686, 0.37192314],
       [0.864955  , 0.135045  ],
       [0.71420117, 0.28579883],
       [0.09817021, 0.90182979],
       [0.13152723, 0.86847277],
       [0.8526205 , 0.1473795 ],
       [0.65584626, 0.34415374],
       [0.01820681, 0.98179319],
       [0.19028046, 0.80971954],
       [0.70594399, 0.29405601],
       [0.12675459, 0.87324541],
       [0.72324013, 0.27675987],
       [0.84911583, 0.15088417],
       [0.67163116, 0.32836884],
       [0.20013292, 0.79986708],
       [0.23997463, 0.76002537],
       [0.06877997, 0.93122003],
       [0.35824199, 0.64175801],
       [0.10615259, 0.89384741],
       [0.09039993, 0.90960007],
       [0.31020485, 0.68979515],
       [0.86889272, 0.13110728],
       [0.45415522, 0.54584478],
       [0.17091758, 0.82908242],
       [0.32866369, 0.67133631],
       [0.91377933, 0.08622067],
       [0.81825882, 0.18174118],
       [0.46226973, 0.53773027],
       [0.80248763, 0.19751237],
       [0.18240688, 0.81759312],
       [0.81148616, 0.18851384],
       [0.73526117, 0.26473883],
       [0.04560252, 0.95439748],
       [0.7860552 , 0.2139448 ]])

In [26]:
from sklearn.metrics import accuracy_score,precision_score,recall_score

In [27]:

accuracy = accuracy_score(y_test,y_pred)
print(accuracy)
precision = precision_score(y_test,y_pred)
print(precision)
recall = recall_score(y_test,y_pred)
print(recall)

0.7653631284916201
0.6753246753246753
0.7536231884057971